version: "3.8"

services:
  fastapi:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - shared_data:/backend/static  # Mount shared volume to /app/static in the FastAPI container
    environment:
      - OPENAI_API_KEY=XXXX
      - MONGO_URI=mongodb://localhost:27017/brainrot
      - JWT_SECRET=XXXX
      - JWT_ALGORITHM=XXXX
      - GOOGLE_CLIENT_ID=XXXX
      - GOOGLE_CLIENT_SECRET=XXXX
    depends_on:
      - mongodb
    networks:
      - backend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    networks:
      - backend
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - shared_data:/data/db  # Mount shared volume to /data/db in the MongoDB container
    networks:
      - backend

volumes:
  shared_data:  # Declare a named volume

networks:
  backend:  # Define a custom network
    driver: bridge
